apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: my-test-app
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/Kalasritha/My__project__scripts.git
   targetRevision: HEAD
   path: k8s/manifests
 destination:
   server: https://kubernetes.default.svc
   namespace: my-app
 syncPolicy:
   automated:
     prune: true
     selfHeal: true