name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest                  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  




      - name: Install Maven
        run: |
            sudo apt-get update
            sudo apt-get install -y maven
            mvn -version
        
      - name: compile with Maven
        run: pwd && ls &&  cd demo && mvn clean compile
       

      - name: Run unit test
        run: cd demo && mvn test
    

      - name: Build JAR
        run:  cd demo && mvn  package
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Build and push Docker image
        run: |
          cd demo && docker build -t ${{ secrets.DOCKER_USERNAME }}/my-test-app:${{ github.sha }} .
      
          docker push ${{ secrets.DOCKER_USERNAME }}/my-test-app:${{ github.sha}}

  Update-newtag-in-helm-chart:
    needs: build
    runs-on: ubuntu-latest
    steps:      
      - name: Update tag in Helm chart
      
        run: |
          pwd
          ls -R
          sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" charts/my-test-app-chart/values.yaml

         
      #- name: Commit and push changes
      #  run: |
      #    git config --global user.email "srithu0004@gmail.com"
      #    git config --global user.name "Kalasritha"
      #    git add /my-test-app-chart/values.yaml
      #    git commit -m "Update tag in Helm chart"
      #    git push
      #  env:
      #    TOKEN: ${{ secrets.TOKEN }}